package ar.Ziade.personal_finance.mapper;


import ar.Ziade.personal_finance.dtos.account.AccountDto;
import ar.Ziade.personal_finance.dtos.account.NewAccountDto;
import ar.Ziade.personal_finance.entities.account.AccountEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

/**
 * Converts a {@link NewAccountDto} into an {@link AccountEntity}.
 *
 * Why this mapping is needed:
 * The DTO field is named "currency"
 * The entity field is named "currencyType"
 * Since the names differ, we must explicitly define the mapping.
 *
 * @param "NewAccountDto" the incoming request object containing
 *                      account creation data
 * @return a new AccountEntity instance ready to be persisted
 *
 * Important:
 * - Fields with identical names (name, accountType, balanceInCents)
 *   are mapped automatically.
 * - The ID is not set here because it is generated by the database.
 */
@Mapper(componentModel = "spring")
public interface AccountMapper {


    @Mapping(target = "currencyType", // field name in AccountEntity
            source = "currency") //field name in AccountDto
    AccountEntity toEntity(NewAccountDto newAccountDto);

    /**
     * Converts an {@link AccountEntity} into an {@link AccountDto}.
     *
     * This is used when returning data to the client.
     *
     * Since most field names match between entity and DTO,
     * MapStruct automatically maps them without explicit configuration.
     *
     * @param accountEntity the persisted entity retrieved from the database
     * @return an AccountDto ready to be sent as an API response
     */
    @Mapping(target = "currency", source = "currencyType")
    AccountDto toDto(AccountEntity accountEntity);

    @Mapping(target = "id", ignore = true) //to never overwrrite the id
    @Mapping(target = "currencyType", source = "currency")
    void updateAccount(NewAccountDto newAccountDto, @MappingTarget AccountEntity accountEntity);
}
